#! /bin/bash
rsync -aurp --exclude='.DS_Store' ~/Library/Application\ Support/LOVE/demirogue/ruleset ~/demirogue/src/resource
rsync -aurp --exclude='.DS_Store' ~/demirogue/src/resource/ruleset ~/Library/Application\ Support/LOVE/demirogue
