#! /bin/bash
rsync -aurp --exclude='.DS_Store' ~/Library/Application\ Support/LOVE/demirogue/rulesets ~/demirogue/src/resources
rsync -aurp --exclude='.DS_Store' ~/demirogue/src/resources/rulesets ~/Library/Application\ Support/LOVE/demirogue
